name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8# Specify the desired Terraform version

      # Step 3: Configure Azure Credentials
     # - name: 'Set up Azure credentials'
      #  uses:  azure/setup-azure@v1
       # with:
        #  azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Plan Terraform changes
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve
